#========================================================
# Top-level constraint file for Xiangshan on VCU128
# Based on Vivado 2025.1
# Author: Shiqi Liu (changyisong@ict.ac.cn)
# Date: 05/02/2026
#========================================================

# Global clock
create_clock -period 5.000 -name gclk [get_ports gclk_clk_p]

set_property PACKAGE_PIN CN67 [get_ports gclk_clk_p]
set_property PACKAGE_PIN CN66 [get_ports gclk_clk_n]

set_property IOSTANDARD LVDS15 [get_ports gclk_clk_p]
set_property IOSTANDARD LVDS15 [get_ports gclk_clk_n]

# PCIe EP GT reference clock
create_clock -period 10.000 -name pcie_ep_ref_clk -waveform {0.000 5.000} [get_ports pcie_ep_gt_ref_clk_clk_p]

set_property PACKAGE_PIN BR71 [get_ports {pcie_ep_gt_ref_clk_clk_p[0]}]

# PL DDR reference clock SLR2
create_clock -period 5.000 -name ddr4_mig_sys_clk -waveform {0.000 2.500} [get_ports ddr4_mig_sys_clk_clk_p]

set_property IOSTANDARD LVDS15 [get_ports ddr4_mig_sys_clk_clk_n]
set_property IOSTANDARD LVDS15 [get_ports ddr4_mig_sys_clk_clk_p]

set_property PACKAGE_PIN CN64 [get_ports ddr4_mig_sys_clk_clk_n]
set_property PACKAGE_PIN CM63 [get_ports ddr4_mig_sys_clk_clk_p]

# PCIe EP perstn physical location
set_property PACKAGE_PIN BK68 [get_ports pcie_ep_perstn]
set_property IOSTANDARD LVCMOS33 [get_ports pcie_ep_perstn]
set_property PULLUP true [get_ports pcie_ep_perstn]

# LED
#set_property PACKAGE_PIN AA17 [get_ports ddr4_mig_calib_done]
#set_property IOSTANDARD LVCMOS18 [get_ports ddr4_mig_calib_done]

#set_property PACKAGE_PIN AA16 [get_ports pcie_ep_phy_ready]
#set_property IOSTANDARD LVCMOS18 [get_ports pcie_ep_phy_ready]

#set_property PACKAGE_PIN AA15 [get_ports pcie_ep_lnk_up]
#set_property IOSTANDARD LVCMOS18 [get_ports pcie_ep_lnk_up]

# APCP DDR
set_property PACKAGE_PIN CN69 [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN CY60 [get_ports c0_ddr4_act_n]

set_property PACKAGE_PIN CV60 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN CJ59 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN CU58 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN CW60 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN CD60 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN CF61 [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN CE60 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN CD59 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN CL59 [get_ports {c0_ddr4_adr[16]}]
set_property PACKAGE_PIN CJ60 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN CM59 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN CM61 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN CV59 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN CU59 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN CK60 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN CW58 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN CG61 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN CN61 [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN CN59 [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN CL60 [get_ports {c0_ddr4_bg[0]}]
set_property PACKAGE_PIN CW59 [get_ports {c0_ddr4_bg[1]}]
set_property PACKAGE_PIN CU61 [get_ports {c0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN CV61 [get_ports {c0_ddr4_ck_c[1]}]
set_property PACKAGE_PIN CT61 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN CU62 [get_ports {c0_ddr4_ck_t[1]}]
set_property PACKAGE_PIN CJ58 [get_ports {c0_ddr4_cke[0]}]
set_property PACKAGE_PIN CN60 [get_ports {c0_ddr4_cke[1]}]
set_property PACKAGE_PIN CH59 [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN CH61 [get_ports {c0_ddr4_cs_n[1]}]
set_property PACKAGE_PIN CY68 [get_ports {c0_ddr4_dm_n[0]}]
set_property PACKAGE_PIN CT66 [get_ports {c0_ddr4_dm_n[1]}]
set_property PACKAGE_PIN CK67 [get_ports {c0_ddr4_dm_n[2]}]
set_property PACKAGE_PIN CF69 [get_ports {c0_ddr4_dm_n[3]}]
set_property PACKAGE_PIN DA65 [get_ports {c0_ddr4_dm_n[4]}]
set_property PACKAGE_PIN CW64 [get_ports {c0_ddr4_dm_n[5]}]
set_property PACKAGE_PIN CJ65 [get_ports {c0_ddr4_dm_n[6]}]
set_property PACKAGE_PIN CG63 [get_ports {c0_ddr4_dm_n[7]}]
set_property PACKAGE_PIN DB59 [get_ports {c0_ddr4_dm_n[8]}]
set_property PACKAGE_PIN DB66 [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN DC67 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN CT69 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN CU67 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN CR68 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN CV67 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN CU68 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN CU69 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN CM69 [get_ports {c0_ddr4_dq[16]}]
set_property PACKAGE_PIN CM67 [get_ports {c0_ddr4_dq[17]}]
set_property PACKAGE_PIN CK68 [get_ports {c0_ddr4_dq[18]}]
set_property PACKAGE_PIN CJ68 [get_ports {c0_ddr4_dq[19]}]
set_property PACKAGE_PIN DA66 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN CM66 [get_ports {c0_ddr4_dq[20]}]
set_property PACKAGE_PIN CM68 [get_ports {c0_ddr4_dq[21]}]
set_property PACKAGE_PIN CJ69 [get_ports {c0_ddr4_dq[22]}]
set_property PACKAGE_PIN CJ67 [get_ports {c0_ddr4_dq[23]}]
set_property PACKAGE_PIN CG67 [get_ports {c0_ddr4_dq[24]}]
set_property PACKAGE_PIN CG68 [get_ports {c0_ddr4_dq[25]}]
set_property PACKAGE_PIN CE67 [get_ports {c0_ddr4_dq[26]}]
set_property PACKAGE_PIN CG66 [get_ports {c0_ddr4_dq[27]}]
set_property PACKAGE_PIN CG69 [get_ports {c0_ddr4_dq[28]}]
set_property PACKAGE_PIN CH69 [get_ports {c0_ddr4_dq[29]}]
set_property PACKAGE_PIN CW67 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN CE68 [get_ports {c0_ddr4_dq[30]}]
set_property PACKAGE_PIN CF66 [get_ports {c0_ddr4_dq[31]}]
set_property PACKAGE_PIN DA64 [get_ports {c0_ddr4_dq[32]}]
set_property PACKAGE_PIN DC64 [get_ports {c0_ddr4_dq[33]}]
set_property PACKAGE_PIN DB63 [get_ports {c0_ddr4_dq[34]}]
set_property PACKAGE_PIN CY65 [get_ports {c0_ddr4_dq[35]}]
set_property PACKAGE_PIN DA63 [get_ports {c0_ddr4_dq[36]}]
set_property PACKAGE_PIN DC66 [get_ports {c0_ddr4_dq[37]}]
set_property PACKAGE_PIN CW65 [get_ports {c0_ddr4_dq[38]}]
set_property PACKAGE_PIN DC65 [get_ports {c0_ddr4_dq[39]}]
set_property PACKAGE_PIN CY67 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN CU64 [get_ports {c0_ddr4_dq[40]}]
set_property PACKAGE_PIN CY63 [get_ports {c0_ddr4_dq[41]}]
set_property PACKAGE_PIN DC62 [get_ports {c0_ddr4_dq[42]}]
set_property PACKAGE_PIN CV62 [get_ports {c0_ddr4_dq[43]}]
set_property PACKAGE_PIN CU63 [get_ports {c0_ddr4_dq[44]}]
set_property PACKAGE_PIN CY62 [get_ports {c0_ddr4_dq[45]}]
set_property PACKAGE_PIN DB62 [get_ports {c0_ddr4_dq[46]}]
set_property PACKAGE_PIN CW62 [get_ports {c0_ddr4_dq[47]}]
set_property PACKAGE_PIN CF65 [get_ports {c0_ddr4_dq[48]}]
set_property PACKAGE_PIN CL64 [get_ports {c0_ddr4_dq[49]}]
set_property PACKAGE_PIN DB68 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN CH64 [get_ports {c0_ddr4_dq[50]}]
set_property PACKAGE_PIN CG64 [get_ports {c0_ddr4_dq[51]}]
set_property PACKAGE_PIN CM64 [get_ports {c0_ddr4_dq[52]}]
set_property PACKAGE_PIN CK63 [get_ports {c0_ddr4_dq[53]}]
set_property PACKAGE_PIN CH65 [get_ports {c0_ddr4_dq[54]}]
set_property PACKAGE_PIN CL63 [get_ports {c0_ddr4_dq[55]}]
set_property PACKAGE_PIN CF63 [get_ports {c0_ddr4_dq[56]}]
set_property PACKAGE_PIN CE62 [get_ports {c0_ddr4_dq[57]}]
set_property PACKAGE_PIN CJ63 [get_ports {c0_ddr4_dq[58]}]
set_property PACKAGE_PIN CJ62 [get_ports {c0_ddr4_dq[59]}]
set_property PACKAGE_PIN CY66 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN CE63 [get_ports {c0_ddr4_dq[60]}]
set_property PACKAGE_PIN CH62 [get_ports {c0_ddr4_dq[61]}]
set_property PACKAGE_PIN CJ64 [get_ports {c0_ddr4_dq[62]}]
set_property PACKAGE_PIN CF64 [get_ports {c0_ddr4_dq[63]}]
set_property PACKAGE_PIN DA61 [get_ports {c0_ddr4_dq[64]}]
set_property PACKAGE_PIN DA60 [get_ports {c0_ddr4_dq[65]}]
set_property PACKAGE_PIN DB61 [get_ports {c0_ddr4_dq[66]}]
set_property PACKAGE_PIN DC61 [get_ports {c0_ddr4_dq[67]}]
set_property PACKAGE_PIN DA59 [get_ports {c0_ddr4_dq[68]}]
set_property PACKAGE_PIN DC59 [get_ports {c0_ddr4_dq[69]}]
set_property PACKAGE_PIN DB67 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN DC60 [get_ports {c0_ddr4_dq[70]}]
set_property PACKAGE_PIN CY61 [get_ports {c0_ddr4_dq[71]}]
set_property PACKAGE_PIN CV66 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN CT68 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN CW68 [get_ports {c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN CR66 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN CH66 [get_ports {c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN CE66 [get_ports {c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN CV64 [get_ports {c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN CT63 [get_ports {c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN CE65 [get_ports {c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN CD62 [get_ports {c0_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN DA58 [get_ports {c0_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN CV69 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN CR67 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN CH67 [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN CD66 [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN CV65 [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN CT64 [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN CD65 [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN CD63 [get_ports {c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN CY58 [get_ports {c0_ddr4_dqs_t[8]}]
set_property PACKAGE_PIN CM62 [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN CF60 [get_ports {c0_ddr4_odt[1]}]

set_property INTERNAL_VREF 0.6 [get_iobanks 705]

# HGCP PCIe EP
set_property PACKAGE_PIN BL80 [get_ports {pcie_ep_grx_p[4]}]
set_property PACKAGE_PIN BL81 [get_ports {pcie_ep_grx_n[4]}]
set_property PACKAGE_PIN BL75 [get_ports {pcie_ep_gtx_p[4]}]
set_property PACKAGE_PIN BL76 [get_ports {pcie_ep_gtx_n[4]}]
set_property PACKAGE_PIN BK82 [get_ports {pcie_ep_grx_p[5]}]
set_property PACKAGE_PIN BK83 [get_ports {pcie_ep_grx_n[5]}]
set_property PACKAGE_PIN BK77 [get_ports {pcie_ep_gtx_p[5]}]
set_property PACKAGE_PIN BK78 [get_ports {pcie_ep_gtx_n[5]}]
set_property PACKAGE_PIN BJ80 [get_ports {pcie_ep_grx_p[6]}]
set_property PACKAGE_PIN BJ81 [get_ports {pcie_ep_grx_n[6]}]
set_property PACKAGE_PIN BK73 [get_ports {pcie_ep_gtx_p[6]}]
set_property PACKAGE_PIN BK74 [get_ports {pcie_ep_gtx_n[6]}]
set_property PACKAGE_PIN BH82 [get_ports {pcie_ep_grx_p[7]}]
set_property PACKAGE_PIN BH83 [get_ports {pcie_ep_grx_n[7]}]
set_property PACKAGE_PIN BJ75 [get_ports {pcie_ep_gtx_p[7]}]
set_property PACKAGE_PIN BJ76 [get_ports {pcie_ep_gtx_n[7]}]
set_property PACKAGE_PIN BP82 [get_ports {pcie_ep_grx_p[0]}]
set_property PACKAGE_PIN BP83 [get_ports {pcie_ep_grx_n[0]}]
set_property PACKAGE_PIN BP73 [get_ports {pcie_ep_gtx_p[0]}]
set_property PACKAGE_PIN BP74 [get_ports {pcie_ep_gtx_n[0]}]
set_property PACKAGE_PIN BP78 [get_ports {pcie_ep_grx_p[1]}]
set_property PACKAGE_PIN BP79 [get_ports {pcie_ep_grx_n[1]}]
set_property PACKAGE_PIN BN75 [get_ports {pcie_ep_gtx_p[1]}]
set_property PACKAGE_PIN BN76 [get_ports {pcie_ep_gtx_n[1]}]
set_property PACKAGE_PIN BN80 [get_ports {pcie_ep_grx_p[2]}]
set_property PACKAGE_PIN BN81 [get_ports {pcie_ep_grx_n[2]}]
set_property PACKAGE_PIN BM77 [get_ports {pcie_ep_gtx_p[2]}]
set_property PACKAGE_PIN BM78 [get_ports {pcie_ep_gtx_n[2]}]
set_property PACKAGE_PIN BM82 [get_ports {pcie_ep_grx_p[3]}]
set_property PACKAGE_PIN BM83 [get_ports {pcie_ep_grx_n[3]}]
set_property PACKAGE_PIN BM73 [get_ports {pcie_ep_gtx_p[3]}]
set_property PACKAGE_PIN BM74 [get_ports {pcie_ep_gtx_n[3]}]

# Timing constraints
set_multicycle_path -setup -to [get_pins -filter {REF_PIN_NAME=~PCIELTSSM[*]} -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ ADVANCED.GT.* }]] 2
set_multicycle_path -hold  -to [get_pins -filter {REF_PIN_NAME=~PCIELTSSM[*]} -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ ADVANCED.GT.* }]] 1

# Debug Hub
