module xstop_wrapper (
  input          clk,
  input          rst,
  input          rtc_clk,

  input          peripheral_awready,
  output         peripheral_awvalid,
  output [1:0]   peripheral_awid,
  output [30:0]  peripheral_awaddr,
  output [7:0]   peripheral_awlen,
  output [2:0]   peripheral_awsize,
  output [1:0]   peripheral_awburst,
  output         peripheral_awlock,
  output [3:0]   peripheral_awcache,
  output [2:0]   peripheral_awprot,
  output [3:0]   peripheral_awqos,
  input          peripheral_wready,
  output         peripheral_wvalid,
  output [63:0]  peripheral_wdata,
  output [7:0]   peripheral_wstrb,
  output         peripheral_wlast,
  output         peripheral_bready,
  input          peripheral_bvalid,
  input  [1:0]   peripheral_bid,
  input  [1:0]   peripheral_bresp,
  input          peripheral_arready,
  output         peripheral_arvalid,
  output [1:0]   peripheral_arid,
  output [30:0]  peripheral_araddr,
  output [7:0]   peripheral_arlen,
  output [2:0]   peripheral_arsize,
  output [1:0]   peripheral_arburst,
  output         peripheral_arlock,
  output [3:0]   peripheral_arcache,
  output [2:0]   peripheral_arprot,
  output [3:0]   peripheral_arqos,
  output         peripheral_rready,
  input          peripheral_rvalid,
  input  [1:0]   peripheral_rid,
  input  [63:0]  peripheral_rdata,
  input  [1:0]   peripheral_rresp,
  input          peripheral_rlast,

  input          memory_awready,
  output         memory_awvalid,
  output [13:0]  memory_awid,
  output [47:0]  memory_awaddr,
  output [7:0]   memory_awlen,
  output [2:0]   memory_awsize,
  output [1:0]   memory_awburst,
  output         memory_awlock,
  output [3:0]   memory_awcache,
  output [2:0]   memory_awprot,
  output [3:0]   memory_awqos,
  input          memory_wready,
  output         memory_wvalid,
  output [255:0] memory_wdata,
  output [31:0]  memory_wstrb,
  output         memory_wlast,
  output         memory_bready,
  input          memory_bvalid,
  input  [13:0]  memory_bid,
  input  [1:0]   memory_bresp,
  input          memory_arready,
  output         memory_arvalid,
  output [13:0]  memory_arid,
  output [47:0]  memory_araddr,
  output [7:0]   memory_arlen,
  output [2:0]   memory_arsize,
  output [1:0]   memory_arburst,
  output         memory_arlock,
  output [3:0]   memory_arcache,
  output [2:0]   memory_arprot,
  output [3:0]   memory_arqos,
  output         memory_rready,
  input          memory_rvalid,
  input  [13:0]  memory_rid,
  input  [255:0] memory_rdata,
  input  [1:0]   memory_rresp,
  input          memory_rlast,

  input          jtag_tck,
  input          jtag_tms,
  input          jtag_tdi,
  output         jtag_tdo_data,
  output         jtag_tdo_driven,
  input          jtag_reset,
  input  [10:0]  jtag_mfr_id,
  input  [15:0]  jtag_part_number,
  input  [3:0]   jtag_version,

  output         riscv_halt,
  output         riscv_critical_error,
  output [63:0]  trace_cause,
  output [49:0]  trace_tval,
  output [2:0]   trace_priv,
  output [63:0]  trace_mstatus,
  output [2:0]   trace_valid,
  output [149:0] trace_iaddr,
  output [11:0]  trace_itype,
  output [20:0]  trace_iretire,
  output [2:0]   trace_ilastsize,

  input  [47:0]  rst_vec,
  input  [63:0]  ext_intrs
);

  // XSTop derives its RTC internally; rtc_clk remains for the role interface.

  XSTop xstop (
    .nmi_0_0(1'b0),
    .nmi_0_1(1'b0),
    .peripheral_awready(peripheral_awready),
    .peripheral_awvalid(peripheral_awvalid),
    .peripheral_awid(peripheral_awid),
    .peripheral_awaddr(peripheral_awaddr),
    .peripheral_awlen(peripheral_awlen),
    .peripheral_awsize(peripheral_awsize),
    .peripheral_awburst(peripheral_awburst),
    .peripheral_awlock(peripheral_awlock),
    .peripheral_awcache(peripheral_awcache),
    .peripheral_awprot(peripheral_awprot),
    .peripheral_awqos(peripheral_awqos),
    .peripheral_wready(peripheral_wready),
    .peripheral_wvalid(peripheral_wvalid),
    .peripheral_wdata(peripheral_wdata),
    .peripheral_wstrb(peripheral_wstrb),
    .peripheral_wlast(peripheral_wlast),
    .peripheral_bready(peripheral_bready),
    .peripheral_bvalid(peripheral_bvalid),
    .peripheral_bid(peripheral_bid),
    .peripheral_bresp(peripheral_bresp),
    .peripheral_arready(peripheral_arready),
    .peripheral_arvalid(peripheral_arvalid),
    .peripheral_arid(peripheral_arid),
    .peripheral_araddr(peripheral_araddr),
    .peripheral_arlen(peripheral_arlen),
    .peripheral_arsize(peripheral_arsize),
    .peripheral_arburst(peripheral_arburst),
    .peripheral_arlock(peripheral_arlock),
    .peripheral_arcache(peripheral_arcache),
    .peripheral_arprot(peripheral_arprot),
    .peripheral_arqos(peripheral_arqos),
    .peripheral_rready(peripheral_rready),
    .peripheral_rvalid(peripheral_rvalid),
    .peripheral_rid(peripheral_rid),
    .peripheral_rdata(peripheral_rdata),
    .peripheral_rresp(peripheral_rresp),
    .peripheral_rlast(peripheral_rlast),
    .memory_awready(memory_awready),
    .memory_awvalid(memory_awvalid),
    .memory_awid(memory_awid),
    .memory_awaddr(memory_awaddr),
    .memory_awlen(memory_awlen),
    .memory_awsize(memory_awsize),
    .memory_awburst(memory_awburst),
    .memory_awlock(memory_awlock),
    .memory_awcache(memory_awcache),
    .memory_awprot(memory_awprot),
    .memory_awqos(memory_awqos),
    .memory_wready(memory_wready),
    .memory_wvalid(memory_wvalid),
    .memory_wdata(memory_wdata),
    .memory_wstrb(memory_wstrb),
    .memory_wlast(memory_wlast),
    .memory_bready(memory_bready),
    .memory_bvalid(memory_bvalid),
    .memory_bid(memory_bid),
    .memory_bresp(memory_bresp),
    .memory_arready(memory_arready),
    .memory_arvalid(memory_arvalid),
    .memory_arid(memory_arid),
    .memory_araddr(memory_araddr),
    .memory_arlen(memory_arlen),
    .memory_arsize(memory_arsize),
    .memory_arburst(memory_arburst),
    .memory_arlock(memory_arlock),
    .memory_arcache(memory_arcache),
    .memory_arprot(memory_arprot),
    .memory_arqos(memory_arqos),
    .memory_rready(memory_rready),
    .memory_rvalid(memory_rvalid),
    .memory_rid(memory_rid),
    .memory_rdata(memory_rdata),
    .memory_rresp(memory_rresp),
    .memory_rlast(memory_rlast),
    .io_clock(clk),
    .io_reset(rst),
    .io_rtc_clock(rtc_clk),
    .io_sram_config(16'b0),
    .io_extIntrs(ext_intrs),
    .io_pll0_lock(1'b0),
    .io_pll0_ctrl_0(),
    .io_pll0_ctrl_1(),
    .io_pll0_ctrl_2(),
    .io_pll0_ctrl_3(),
    .io_pll0_ctrl_4(),
    .io_pll0_ctrl_5(),
    .io_systemjtag_jtag_TCK(jtag_tck),
    .io_systemjtag_jtag_TMS(jtag_tms),
    .io_systemjtag_jtag_TDI(jtag_tdi),
    .io_systemjtag_jtag_TDO_data(jtag_tdo_data),
    .io_systemjtag_jtag_TDO_driven(jtag_tdo_driven),
    .io_systemjtag_reset(jtag_reset),
    .io_systemjtag_mfr_id(jtag_mfr_id),
    .io_systemjtag_part_number(jtag_part_number),
    .io_systemjtag_version(jtag_version),
    .io_debug_reset(),
    .io_cacheable_check_req_0_valid(1'b0),
    .io_cacheable_check_req_0_bits_addr(48'b0),
    .io_cacheable_check_req_0_bits_size(2'b0),
    .io_cacheable_check_req_0_bits_cmd(3'b0),
    .io_cacheable_check_req_1_valid(1'b0),
    .io_cacheable_check_req_1_bits_addr(48'b0),
    .io_cacheable_check_req_1_bits_size(2'b0),
    .io_cacheable_check_req_1_bits_cmd(3'b0),
    .io_cacheable_check_resp_0_ld(),
    .io_cacheable_check_resp_0_st(),
    .io_cacheable_check_resp_0_instr(),
    .io_cacheable_check_resp_0_mmio(),
    .io_cacheable_check_resp_0_atomic(),
    .io_cacheable_check_resp_1_ld(),
    .io_cacheable_check_resp_1_st(),
    .io_cacheable_check_resp_1_instr(),
    .io_cacheable_check_resp_1_mmio(),
    .io_cacheable_check_resp_1_atomic(),
    .io_riscv_halt_0(riscv_halt),
    .io_riscv_critical_error_0(riscv_critical_error),
    .io_riscv_rst_vec_0(rst_vec),
    .io_traceCoreInterface_0_fromEncoder_enable(1'b0),
    .io_traceCoreInterface_0_fromEncoder_stall(1'b0),
    .io_traceCoreInterface_0_toEncoder_cause(trace_cause),
    .io_traceCoreInterface_0_toEncoder_tval(trace_tval),
    .io_traceCoreInterface_0_toEncoder_priv(trace_priv),
    .io_traceCoreInterface_0_toEncoder_mstatus(trace_mstatus),
    .io_traceCoreInterface_0_toEncoder_valid(trace_valid),
    .io_traceCoreInterface_0_toEncoder_iaddr(trace_iaddr),
    .io_traceCoreInterface_0_toEncoder_itype(trace_itype),
    .io_traceCoreInterface_0_toEncoder_iretire(trace_iretire),
    .io_traceCoreInterface_0_toEncoder_ilastsize(trace_ilastsize)
  );

endmodule
