#========================================================
# Top-level constraint file for Xiangshan on VCU128
# Based on Vivado 2025.1
# Author: Shiqi Liu (changyisong@ict.ac.cn)
# Date: 05/02/2026
#========================================================

# Global clock
create_clock -period 5.000 -name gclk [get_ports gclk_clk_p]

set_property PACKAGE_PIN CN67 [get_ports gclk_clk_p]
set_property PACKAGE_PIN CN66 [get_ports gclk_clk_n]

set_property IOSTANDARD LVDS15 [get_ports gclk_clk_p]
set_property IOSTANDARD LVDS15 [get_ports gclk_clk_n]

# PCIe EP GT reference clock
create_clock -period 10.000 -name pcie_ep_ref_clk -waveform {0.000 5.000} [get_ports pcie_ep_gt_ref_clk_clk_p]

set_property PACKAGE_PIN BR71 [get_ports {pcie_ep_gt_ref_clk_clk_p[0]}]

# PD-AS200 DDR4_1 200 MHz reference clock
create_clock -period 5.000 -name ddr4_mig_sys_clk -waveform {0.000 2.500} [get_ports ddr4_mig_sys_clk_clk_p]

set_property IOSTANDARD LVDS15 [get_ports ddr4_mig_sys_clk_clk_n]
set_property IOSTANDARD LVDS15 [get_ports ddr4_mig_sys_clk_clk_p]

set_property PACKAGE_PIN CP82 [get_ports ddr4_mig_sys_clk_clk_n]
set_property PACKAGE_PIN CP83 [get_ports ddr4_mig_sys_clk_clk_p]

# PCIe EP perstn physical location
set_property PACKAGE_PIN BK68 [get_ports pcie_ep_perstn]
set_property IOSTANDARD LVCMOS33 [get_ports pcie_ep_perstn]
set_property PULLUP true [get_ports pcie_ep_perstn]

# LED
#set_property PACKAGE_PIN AA17 [get_ports ddr4_mig_calib_done]
#set_property IOSTANDARD LVCMOS18 [get_ports ddr4_mig_calib_done]

#set_property PACKAGE_PIN AA16 [get_ports pcie_ep_phy_ready]
#set_property IOSTANDARD LVCMOS18 [get_ports pcie_ep_phy_ready]

#set_property PACKAGE_PIN AA15 [get_ports pcie_ep_lnk_up]
#set_property IOSTANDARD LVCMOS18 [get_ports pcie_ep_lnk_up]

# PD-AS200 DDR4_1 memory interface (manual Section 5.7)
set_property PACKAGE_PIN CR83 [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN CY75 [get_ports c0_ddr4_act_n]

set_property PACKAGE_PIN CV77 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN CW74 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN DC76 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN CM76 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN CL76 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN CR77 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN CR76 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN CV76 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN DC77 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN CW75 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN CU76 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN CM78 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN CT75 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN DA76 [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN CN77 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN CJ77 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN DB76 [get_ports {c0_ddr4_adr[16]}]

set_property PACKAGE_PIN CT78 [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN CW77 [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN CT74 [get_ports {c0_ddr4_bg[0]}]
set_property PACKAGE_PIN CY76 [get_ports {c0_ddr4_bg[1]}]

set_property PACKAGE_PIN CV74 [get_ports {c0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN DA78 [get_ports {c0_ddr4_ck_c[1]}]
set_property PACKAGE_PIN CU74 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN CY77 [get_ports {c0_ddr4_ck_t[1]}]
set_property PACKAGE_PIN DC75 [get_ports {c0_ddr4_cke[0]}]
set_property PACKAGE_PIN DA75 [get_ports {c0_ddr4_cke[1]}]
set_property PACKAGE_PIN DB77 [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN CP77 [get_ports {c0_ddr4_cs_n[1]}]

set_property PACKAGE_PIN CL71 [get_ports {c0_ddr4_dm_n[0]}]
set_property PACKAGE_PIN CP70 [get_ports {c0_ddr4_dm_n[1]}]
set_property PACKAGE_PIN CM79 [get_ports {c0_ddr4_dm_n[2]}]
set_property PACKAGE_PIN CM74 [get_ports {c0_ddr4_dm_n[3]}]
set_property PACKAGE_PIN CU82 [get_ports {c0_ddr4_dm_n[4]}]
set_property PACKAGE_PIN CY81 [get_ports {c0_ddr4_dm_n[5]}]
set_property PACKAGE_PIN CY71 [get_ports {c0_ddr4_dm_n[6]}]
set_property PACKAGE_PIN DB72 [get_ports {c0_ddr4_dm_n[7]}]
set_property PACKAGE_PIN CK83 [get_ports {c0_ddr4_dm_n[8]}]

set_property PACKAGE_PIN CJ73 [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN CM73 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN CL73 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN CK73 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN CN72 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN CM72 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN CJ72 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN CK72 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN CR71 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN CP72 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN CP74 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN CR73 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN CT71 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN CT70 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN CR72 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN CP73 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN CP79 [get_ports {c0_ddr4_dq[16]}]
set_property PACKAGE_PIN CM81 [get_ports {c0_ddr4_dq[17]}]
set_property PACKAGE_PIN CN82 [get_ports {c0_ddr4_dq[18]}]
set_property PACKAGE_PIN CM82 [get_ports {c0_ddr4_dq[19]}]
set_property PACKAGE_PIN CP80 [get_ports {c0_ddr4_dq[20]}]
set_property PACKAGE_PIN CN80 [get_ports {c0_ddr4_dq[21]}]
set_property PACKAGE_PIN CN81 [get_ports {c0_ddr4_dq[22]}]
set_property PACKAGE_PIN CM83 [get_ports {c0_ddr4_dq[23]}]
set_property PACKAGE_PIN CP75 [get_ports {c0_ddr4_dq[24]}]
set_property PACKAGE_PIN CL75 [get_ports {c0_ddr4_dq[25]}]
set_property PACKAGE_PIN CK76 [get_ports {c0_ddr4_dq[26]}]
set_property PACKAGE_PIN CN76 [get_ports {c0_ddr4_dq[27]}]
set_property PACKAGE_PIN CN75 [get_ports {c0_ddr4_dq[28]}]
set_property PACKAGE_PIN CL74 [get_ports {c0_ddr4_dq[29]}]
set_property PACKAGE_PIN CK75 [get_ports {c0_ddr4_dq[30]}]
set_property PACKAGE_PIN CR75 [get_ports {c0_ddr4_dq[31]}]
set_property PACKAGE_PIN CV80 [get_ports {c0_ddr4_dq[32]}]
set_property PACKAGE_PIN CT83 [get_ports {c0_ddr4_dq[33]}]
set_property PACKAGE_PIN CU83 [get_ports {c0_ddr4_dq[34]}]
set_property PACKAGE_PIN CU81 [get_ports {c0_ddr4_dq[35]}]
set_property PACKAGE_PIN CV79 [get_ports {c0_ddr4_dq[36]}]
set_property PACKAGE_PIN CU79 [get_ports {c0_ddr4_dq[37]}]
set_property PACKAGE_PIN CT81 [get_ports {c0_ddr4_dq[38]}]
set_property PACKAGE_PIN CV81 [get_ports {c0_ddr4_dq[39]}]
set_property PACKAGE_PIN DA81 [get_ports {c0_ddr4_dq[40]}]
set_property PACKAGE_PIN CY82 [get_ports {c0_ddr4_dq[41]}]
set_property PACKAGE_PIN DA79 [get_ports {c0_ddr4_dq[42]}]
set_property PACKAGE_PIN DB79 [get_ports {c0_ddr4_dq[43]}]
set_property PACKAGE_PIN CW82 [get_ports {c0_ddr4_dq[44]}]
set_property PACKAGE_PIN CW83 [get_ports {c0_ddr4_dq[45]}]
set_property PACKAGE_PIN DA80 [get_ports {c0_ddr4_dq[46]}]
set_property PACKAGE_PIN DC79 [get_ports {c0_ddr4_dq[47]}]
set_property PACKAGE_PIN CY72 [get_ports {c0_ddr4_dq[48]}]
set_property PACKAGE_PIN CW69 [get_ports {c0_ddr4_dq[49]}]
set_property PACKAGE_PIN DA70 [get_ports {c0_ddr4_dq[50]}]
set_property PACKAGE_PIN CW73 [get_ports {c0_ddr4_dq[51]}]
set_property PACKAGE_PIN CW70 [get_ports {c0_ddr4_dq[52]}]
set_property PACKAGE_PIN DA73 [get_ports {c0_ddr4_dq[53]}]
set_property PACKAGE_PIN DA69 [get_ports {c0_ddr4_dq[54]}]
set_property PACKAGE_PIN CY73 [get_ports {c0_ddr4_dq[55]}]
set_property PACKAGE_PIN DC74 [get_ports {c0_ddr4_dq[56]}]
set_property PACKAGE_PIN DA74 [get_ports {c0_ddr4_dq[57]}]
set_property PACKAGE_PIN DC70 [get_ports {c0_ddr4_dq[58]}]
set_property PACKAGE_PIN DC69 [get_ports {c0_ddr4_dq[59]}]
set_property PACKAGE_PIN DB73 [get_ports {c0_ddr4_dq[60]}]
set_property PACKAGE_PIN DB74 [get_ports {c0_ddr4_dq[61]}]
set_property PACKAGE_PIN DC71 [get_ports {c0_ddr4_dq[62]}]
set_property PACKAGE_PIN DB69 [get_ports {c0_ddr4_dq[63]}]
set_property PACKAGE_PIN CL79 [get_ports {c0_ddr4_dq[64]}]
set_property PACKAGE_PIN CK81 [get_ports {c0_ddr4_dq[65]}]
set_property PACKAGE_PIN CJ83 [get_ports {c0_ddr4_dq[66]}]
set_property PACKAGE_PIN CJ82 [get_ports {c0_ddr4_dq[67]}]
set_property PACKAGE_PIN CK78 [get_ports {c0_ddr4_dq[68]}]
set_property PACKAGE_PIN CJ80 [get_ports {c0_ddr4_dq[69]}]
set_property PACKAGE_PIN CK80 [get_ports {c0_ddr4_dq[70]}]
set_property PACKAGE_PIN CK82 [get_ports {c0_ddr4_dq[71]}]

set_property PACKAGE_PIN CK71 [get_ports {c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN CN70 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN CL80 [get_ports {c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN CJ74 [get_ports {c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN CT79 [get_ports {c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN CW79 [get_ports {c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN CW72 [get_ports {c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN DB71 [get_ports {c0_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN CJ78 [get_ports {c0_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN CJ70 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN CN71 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN CL81 [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN CJ75 [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN CT80 [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN CW80 [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN CV72 [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN DA71 [get_ports {c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN CJ79 [get_ports {c0_ddr4_dqs_t[8]}]

set_property PACKAGE_PIN CP78 [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN CU77 [get_ports {c0_ddr4_odt[1]}]

set_property INTERNAL_VREF 0.6 [get_iobanks 700 701 702]

# HGCP PCIe EP
set_property PACKAGE_PIN BL80 [get_ports {pcie_ep_grx_p[4]}]
set_property PACKAGE_PIN BL81 [get_ports {pcie_ep_grx_n[4]}]
set_property PACKAGE_PIN BL75 [get_ports {pcie_ep_gtx_p[4]}]
set_property PACKAGE_PIN BL76 [get_ports {pcie_ep_gtx_n[4]}]
set_property PACKAGE_PIN BK82 [get_ports {pcie_ep_grx_p[5]}]
set_property PACKAGE_PIN BK83 [get_ports {pcie_ep_grx_n[5]}]
set_property PACKAGE_PIN BK77 [get_ports {pcie_ep_gtx_p[5]}]
set_property PACKAGE_PIN BK78 [get_ports {pcie_ep_gtx_n[5]}]
set_property PACKAGE_PIN BJ80 [get_ports {pcie_ep_grx_p[6]}]
set_property PACKAGE_PIN BJ81 [get_ports {pcie_ep_grx_n[6]}]
set_property PACKAGE_PIN BK73 [get_ports {pcie_ep_gtx_p[6]}]
set_property PACKAGE_PIN BK74 [get_ports {pcie_ep_gtx_n[6]}]
set_property PACKAGE_PIN BH82 [get_ports {pcie_ep_grx_p[7]}]
set_property PACKAGE_PIN BH83 [get_ports {pcie_ep_grx_n[7]}]
set_property PACKAGE_PIN BJ75 [get_ports {pcie_ep_gtx_p[7]}]
set_property PACKAGE_PIN BJ76 [get_ports {pcie_ep_gtx_n[7]}]
set_property PACKAGE_PIN BP82 [get_ports {pcie_ep_grx_p[0]}]
set_property PACKAGE_PIN BP83 [get_ports {pcie_ep_grx_n[0]}]
set_property PACKAGE_PIN BP73 [get_ports {pcie_ep_gtx_p[0]}]
set_property PACKAGE_PIN BP74 [get_ports {pcie_ep_gtx_n[0]}]
set_property PACKAGE_PIN BP78 [get_ports {pcie_ep_grx_p[1]}]
set_property PACKAGE_PIN BP79 [get_ports {pcie_ep_grx_n[1]}]
set_property PACKAGE_PIN BN75 [get_ports {pcie_ep_gtx_p[1]}]
set_property PACKAGE_PIN BN76 [get_ports {pcie_ep_gtx_n[1]}]
set_property PACKAGE_PIN BN80 [get_ports {pcie_ep_grx_p[2]}]
set_property PACKAGE_PIN BN81 [get_ports {pcie_ep_grx_n[2]}]
set_property PACKAGE_PIN BM77 [get_ports {pcie_ep_gtx_p[2]}]
set_property PACKAGE_PIN BM78 [get_ports {pcie_ep_gtx_n[2]}]
set_property PACKAGE_PIN BM82 [get_ports {pcie_ep_grx_p[3]}]
set_property PACKAGE_PIN BM83 [get_ports {pcie_ep_grx_n[3]}]
set_property PACKAGE_PIN BM73 [get_ports {pcie_ep_gtx_p[3]}]
set_property PACKAGE_PIN BM74 [get_ports {pcie_ep_gtx_n[3]}]

# Timing constraints
set_multicycle_path -setup -to [get_pins -filter {REF_PIN_NAME=~PCIELTSSM[*]} -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ ADVANCED.GT.* }]] 2
set_multicycle_path -hold  -to [get_pins -filter {REF_PIN_NAME=~PCIELTSSM[*]} -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ ADVANCED.GT.* }]] 1

# Debug Hub
